### ISSUE TITLE
how to decode?

### ISSUE THREAD

**Issue by Bendikos** [N0rmie/fivem-lua-simple-xor-encrypt#2]
![图片](https://github.com/user-attachments/assets/1434bcf0-f15b-4d38-9fa2-b3040b5988f9)

**Comment by N0rmie** [comment]
Upload the script here and ill decode it

**Comment by Bendikos** [comment]
You are a warm-hearted person. That script is a test I did myself, and it has no practical value. I just want to learn to learn decoding technology.
If you don't want to tell me, I won't be sad about it. 🤝🤝🤝
